dist: bionic
language: go

services:
  - docker

go:
  - 1.15.x
  - 1.14.x
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

cache:
  directories:
    - /home/travis/.cache/go-build
    # - /home/travis/gopath/pkg

before_cache:
  - go clean -testcache
  # - go clean -cache

go_import_path: github.com/percona/rds_exporter

env:
  global:
    # AWS - PMM Autotest account.
    # Travis secrets are not exposed to pull requests from forks: https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions
    - AWS_ACCESS_KEY=AKIAZPBRO3QWGCO72MJZ
    - secure: "tMvScZPnZZBY/RUNt2Xg9wer7sJPPpHkLjTM79qzQ8RvJ1R/SL2SXwILo9L1uoJmJcSvDTnJH9UMV1RLnxHdENsNxkJrykMjQDiECR45aV5XaWbrNYz74oIn4xgoWQYd/vz9H5Z6C2foy/lbd+B//S4hQIQ3hKPd9J2lM8bG3rjt8jiQOfyfGU1NRrKUvt3Bb8Tj5R+btDHPWl+81DLRcQmqjv3dwNA/IJB81bmm6hYrg27SIKyruewjIIi6KVv3bOw6U/ms+7iGSQwp5Rr+5j4LUHkRFvNlXydmFJZcu1RfszUMDjS2akuYuItGYiOrS2Nbdh/51NEVXpH101zvDbAV7RAreGYCCCyAXKna+NrP8RTXSouHKp2s/6H8rDIKb7ASovSqZkSo+ZJmHUGwE/UzdWExohrNQBej/VkWYVwszjLH3K9Vp0zlCd0bs4JezWPqHJYvLa1qIzoEQfsfexUKQeuZM1HUvSaSxXqdWGWQ2sxxtRwdMxJnsKYPOSjNh6zddDmIyBZtDGlezxftRNMDNhK8LHvO1qbyL4E+RdRToGYrYiPVkuACFewhyM/Yvqeo68IFUPcK4l+UcoQYt9p7P/Y15//GRI4RPZKr7CLoxh4dnPoTUZSf/QXTN/05ymiP6cpUWPMDA4m4Zb3u3D2SLVMFRa20OFYqqHQWI2A="
    # REVIEWDOG_GITHUB_API_TOKEN
    - secure: "2BgdTQdJFrXJANqhgOHOTZBL4F8kh1WxoYlG0pMKam7VWooaSiehc18abODUmRkdVoDPen1MpikmAH8ekabkTfkAJ+qxqEUp1pkA20bs18tePUyHS2iGn5hgN9SMrxOb5QB0vHilg0B95BNlIy2kZY6A2+JWn73aqDsFDMV8OMEeA4Mi0KnYtbXmmZ9gqTw+gusfxkVD8RNgXvg4zGmNLS/hLaXFFtmtx9xl7SAbQPvxtj9Po7FUYq9G+qazjg0pRZ9UH6hJQPxIHOumRx447hagL/521X9ZAtlwe17H368M4a7J2Cd6Tm70alktDH3Tsu258PMsKsTqQOHtMOfeOiDshqN2K0AuKatYBsSAshxgDChDe7+Wyi9VV1mlo1zUTEe4bVaBlHZy0VCy5JuzwrxFS2Xz/dXvNIaqlTfzimrPgOavXREDycoKHpcJf6IKvwWX9+JVopTqR7Md3gQIOpRrLJ2wOtAv8KdG6g2wuBe2IMdbXpUOPvBS+SjERuXAp99H4H2irt74HAfTudtvC6MtE/t5BYV4hmuEfX5zKGiZ6xShBasQeRWqsSwi4gWU8k5CpwqbkMt4NMNBWGZuAi01w8fM0QHidqlBOO4drps0N1gbNXUIgR/0S1w8rYzfL4Z2K7bX7L9qYyP09dSeha3MUFiu0w4WCNqPoafYiQo="

install:
  # install reviewdog and golangci-lint
  - curl https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
  - curl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

script:
  - make travis
